services:
  rediscache:
    image: rediscache
    build:
      context: ./RedisCache
      dockerfile: Dockerfile
    ports:
      - "8080:80"  
    environment:
      - ASPNETCORE_URLS=http://+:80

  redis:
    image: redis
    ports:
      - "6379:6379"
